Type annotations. Issue #45
adafruit/Adafruit_CircuitPython_BME680 pull request #49
Opened 2022-04-19 12:43 UTC by billvanleeuwen424

Addressing the type annotations issue. Mostly the same as the last PR I created for the BMP280. 

issue link:
https://github.com/adafruit/Adafruit_CircuitPython_BME680/issues/45

2022-04-19 14:08 UTC, tekktrik requested changes
Thanks so much or the submission!  I added my feedback, let me know if I can help answer any questions or elaborate!

2022-04-19 14:08 UTC, tekktrik commented on adafruit_bme680.py
> +    # Used only for type annotations.
Since we only want this to run in a computer (development) environment, but skip on the microcontroller, we can use the `typing` module to guard from running the rest of the block (since CircuitPython doesn't implement the `typing` module):

```suggestion
    # Used only for type annotations.
    import typing  # pylint: disable=unused-import
```

The `pylint` disable will allow us to still try importing the module while suppressing the typical pylint error :)

2022-04-19 14:08 UTC, tekktrik commented on adafruit_bme680.py
> +    def _read(self, register: int, length: int) -> None:
Since the intention of this method is to service as a blueprint for subclasses of `Adafruit_BME680` (IDEs will warn if this function isn't implemented), it'd be nice to blueprint what type it should return:

```suggestion
    def _read(self, register: int, length: int) -> bytearray:
```

2022-04-19 14:08 UTC, tekktrik commented on adafruit_bme680.py
> +def _read24(arr: bytearray) -> float:
The type for `arr` can actually be further generalized to `circuitpython_typing.ReadableBuffer` which may help if someone ever wants to use `bytes` or something:

```suggestion
def _read24(arr: ReadableBuffer) -> float
```

Just make sure to use `from circuitpython_typing import ReadableBuffer` after the `import typing` line at the top!

2022-04-19 14:08 UTC, tekktrik commented on adafruit_bme680.py
> +    def _write(self, register: int, values) -> None:
The type can also be blueprinted for values:

```suggestion
    def _write(self, register: int, values: ReadableBuffer) -> None:
```

2022-04-19 14:08 UTC, tekktrik commented on adafruit_bme680.py
> +    def _write(self, register: int, values: int) -> None:
The type for values should be something that implements the buffer protocol and can be read from, so its that ReadableBuffer:

```suggestion
    def _write(self, register: int, values: ReadableBuffer) -> None:
```

2022-04-19 14:08 UTC, tekktrik commented on adafruit_bme680.py
> +    ):
Looks like you're missing the `None` return

2022-04-19 14:08 UTC, tekktrik commented on adafruit_bme680.py
> +    def _read(self, register: int, length: int):
Mind adding the `bytearray` return type?

2022-04-19 14:08 UTC, tekktrik commented on adafruit_bme680.py
> +    def _write(self, register: int, values: int):
Looks like the typing is the same as the others:

```suggestion
    def _write(self, register: int, values: ReadableBuffer) -> None:
```

2022-04-19 14:08 UTC, tekktrik commented on adafruit_bme680.py
> +    def _set_spi_mem_page(self, register: int):
Mind adding the `None` return type here?

2022-04-20 01:21 UTC, billvanleeuwen424 commented
Thanks for the super kind, speedy, and helpful review @tekktrik! I appreciate you looking it over and educating me

2022-04-20 01:56 UTC, tekktrik approved these changes

2022-04-20 01:56 UTC, tekktrik commented
My pleasure!  Thanks for taking the time to do this!  Looks good to me!

2022-04-20 01:56 UTC, merged